/**
 * Nexafxtrade Frontend Engine
 * Version: 3.0.0 (May 2026)
 * Description: Core logic for live trading, Socket.io synchronization, and market visualization.
 */

// 1. INITIALIZE REAL-TIME CONNECTION
// Standard connection to the backend server
const socket = io(); 

// 2. LIVE GRAPH CONFIGURATION (Nexafxtrade Market Waves)
const ctx = document.getElementById('tradeChart').getContext('2d');

// Array size of 60 ensures a 1-minute window if updates are every 1 second
let chartData = Array(60).fill(0.00); 
let labels = Array(60).fill('');

const tradeChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: labels,
        datasets: [{
            label: 'Market Rate',
            data: chartData,
            borderColor: '#00ff00', // Nexafxtrade Neon Green
            borderWidth: 2,
            pointRadius: 0, 
            fill: {
                target: 'origin',
                above: 'rgba(0, 255, 0, 0.15)', // Green glow for profit zones
                below: 'rgba(255, 0, 0, 0.15)'  // Red glow for loss zones
            },
            tension: 0.4, // Creates the smooth "wavy" look from image_3.png
        }]
    },
    options: {
        responsive: true,
        maintainAspectRatio: false,
        animation: {
            duration: 400, 
            easing: 'linear'
        },
        scales: {
            x: { display: false },
            y: {
                min: -0.15,
                max: 0.15,
                grid: { color: '#1a1a1a' }, // Subtle grid lines
                ticks: { color: '#555', font: { size: 10 } }
            }
        },
        plugins: { 
            legend: { display: false } 
        }
    }
});

// 3. MARKET UPDATE LISTENER
// This receives the live numbers generated by your backend server
socket.on('market-update', (data) => {
    const rateValue = data.rate;

    // Update the visual rate display in the overlay
    const rateDisplay = document.getElementById('current-rate');
    if (rateDisplay) {
        rateDisplay.innerText = rateValue.toFixed(4);
    }

    // Scroll the graph: Remove the oldest point and add the newest
    chartData.shift();
    chartData.push(rateValue);
    
    // Update the chart without triggering a full re-render ('none') for smoothness
    tradeChart.update('none');
});

// 4. CHAT & WITHDRAWAL NOTIFICATIONS (Social Proof)
const chatFeed = document.getElementById('chat-feed');
const chatInput = document.getElementById('chat-input-field');
const sendBtn = document.getElementById('send-chat-btn');

socket.on('receive-chat', (data) => {
    if (!chatFeed) return;

    const div = document.createElement('div');
    div.className = "chat-msg-container";
    div.style.marginBottom = "10px";
    div.style.fontSize = "0.85rem";

    // Format for System messages (Withdrawal alerts)
    if (data.user === 'System') {
        div.innerHTML = `<span style="color: #ffcc00; font-weight: bold;">[SYSTEM]:</span> <span style="color: #fff;">${data.message}</span>`;
    } else {
        // Format for User messages
        div.innerHTML = `<span style="color: #00ff00; font-weight: bold;">${data.user}:</span> <span style="color: #eee;">${data.message}</span>`;
    }

    chatFeed.appendChild(div);
    
    // Keep the latest message in view
    chatFeed.scrollTop = chatFeed.scrollHeight;

    // Performance: Keep only the last 25 messages in the DOM
    if (chatFeed.children.length > 25) {
        chatFeed.removeChild(chatFeed.children[0]);
    }
});

// Manual Chat Sending
if (sendBtn) {
    sendBtn.onclick = () => {
        const text = chatInput.value.trim();
        if (text !== "") {
            // Sends the message to the backend to be broadcasted to everyone
            socket.emit('send-chat', { user: "User_" + Math.floor(Math.random()*999), message: text });
            chatInput.value = "";
        }
    };
}

// 5. TRADING INTERFACE LOGIC
/**
 * Handles the + , - , and x2 buttons for the trade amount
 */
window.adjustAmount = (val) => {
    const input = document.getElementById('trade-amount');
    if (!input) return;

    let current = parseInt(input.value) || 0;
    
    if (val === 'double') {
        input.value = current * 2;
    } else {
        // Prevents negative numbers
        input.value = Math.max(0, current + val);
    }
};

/**
 * Quick select buttons (100, 200, 500)
 */
window.setSum = (val) => {
    const input = document.getElementById('trade-amount');
    if (input) input.value = val;
};

// 6. EXECUTION BUTTONS
const buyBtn = document.getElementById('buy-btn');
const sellBtn = document.getElementById('sell-btn');

if (buyBtn) {
    buyBtn.onclick = () => {
        const amount = document.getElementById('trade-amount').value;
        socket.emit('place-trade', { type: 'BUY', amount: amount, timestamp: Date.now() });
        console.log("Nexafxtrade: BUY order emitted.");
    };
}

if (sellBtn) {
    sellBtn.onclick = () => {
        const amount = document.getElementById('trade-amount').value;
        socket.emit('place-trade', { type: 'SELL', amount: amount, timestamp: Date.now() });
        console.log("Nexafxtrade: SELL order emitted.");
    };
}

// 7. ACCOUNT SYNC
// Listen for balance updates from the server (e.g., after a trade wins or loses)
socket.on('balance-update', (data) => {
    const balanceDisplay = document.getElementById('user-balance');
    if (balanceDisplay) {
        balanceDisplay.innerText = parseFloat(data.newBalance).toFixed(2);
    }
});

console.log("Nexafxtrade Engine: Fully Operational.");
